import Section from "../../components/partials/section";


export default function StoryPage() {
  return (
    <main className="text-2xl lg:text-3xl">
      <Section className="flex flex-col">
        <h1 className="text-6xl text-color3">Stories</h1> 
        <p className="text-2xl">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec feugiat tellus, non elementum ante. Curabitur ac lacus id ante interdum consectetur quis non metus. Praesent consequat viverra diam vel pharetra. Duis libero est, mattis suscipit volutpat quis, porta a odio. Pellentesque sit amet consequat metus, at viverra lectus. Sed at dui dignissim, placerat diam eu, mollis tellus. Duis gravida turpis a ipsum egestas mollis. Sed aliquet eros rhoncus ligula aliquam sodales. Donec sit amet magna libero. Praesent eu efficitur nibh. Curabitur vel lobortis ipsum. Praesent congue sapien vel metus ultricies consequat sit amet ut tortor. Fusce eu leo ut magna aliquet rhoncus. Cras aliquet hendrerit tortor, id ullamcorper quam mollis at.
          Aenean nec nibh leo. Mauris ac eros elementum, tristique tellus eget, volutpat tellus. Ut eu ante eget justo consequat condimentum a in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis volutpat porttitor nunc, id cursus quam suscipit id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi urna neque, lacinia eget magna ac, efficitur auctor felis. Vivamus eu ante lacinia, accumsan ante malesuada, condimentum nulla. Aenean ac nunc dapibus, tincidunt velit sit amet, rutrum arcu. In nibh eros, scelerisque eu sollicitudin a, imperdiet quis nunc. Nullam nec odio non nisi ultrices rhoncus et sed mi. Quisque erat eros, eleifend non viverra pulvinar, condimentum at nibh. Donec nec massa ex. Etiam id mi est.

            In hac habitasse platea dictumst. Mauris nunc dui, congue eu tincidunt et, mollis id dui. Curabitur at congue massa. Donec eu placerat tellus, nec posuere erat. Curabitur tempor, ante iaculis tempor suscipit, mauris justo posuere ligula, vitae mattis ante diam quis mi. Duis posuere augue sed risus dapibus, non dictum ante accumsan. Donec nisi urna, malesuada nec nunc et, accumsan scelerisque ante. Duis egestas dignissim vulputate. Curabitur porttitor malesuada lectus, in volutpat risus vulputate ac. Fusce risus metus, pulvinar ac nibh quis, semper lobortis odio.

            Etiam eleifend, purus in commodo aliquam, nibh dolor dignissim ligula, sed euismod est velit nec eros. Curabitur id mauris non mi posuere placerat eget quis dolor. Aenean elit purus, tempor vitae molestie eget, aliquet non felis. Sed sed rhoncus magna, et fermentum quam. Donec finibus ante ac est pharetra malesuada. Proin placerat porttitor finibus. Nunc ac viverra libero. Sed eget dolor lorem.

            Maecenas vestibulum pellentesque sapien, vel consectetur ex congue at. Aenean velit velit, consectetur in tempor sed, elementum convallis dolor. Sed interdum justo id neque eleifend porttitor. Fusce consectetur leo purus, nec malesuada massa elementum eget. Integer in elementum velit, eget iaculis lectus. Nulla at tristique urna. Nunc sit amet viverra felis. Phasellus in consectetur tortor, sed consectetur dui. Vestibulum luctus nisl sit amet euismod vehicula. Integer sem lorem, sagittis eu molestie a, lacinia sit amet ex.

            Proin ultricies urna quis sollicitudin venenatis. Sed ante mauris, malesuada quis vehicula ut, suscipit vitae magna. Cras erat eros, convallis a vulputate bibendum, interdum nec odio. Proin et risus faucibus, vulputate magna quis, tincidunt felis. Ut imperdiet purus risus, sit amet suscipit nunc volutpat condimentum. Sed mauris ligula, condimentum ut consectetur vitae, scelerisque ac tortor. Integer at ipsum sed magna vehicula consectetur eu placerat erat. Nam nec ante volutpat, dignissim leo sit amet, convallis nunc.

            Cras et eleifend ipsum. Suspendisse aliquam odio vel eros condimentum bibendum. Ut consequat tellus vel mauris imperdiet, vitae aliquam nibh finibus. Aliquam ultricies libero a mi egestas laoreet. Nunc eu augue eu quam ultrices eleifend. Integer eu quam neque. Morbi faucibus, tellus nec vulputate iaculis, mi elit interdum neque, id egestas eros lorem quis arcu.

            Morbi non tincidunt tortor. Curabitur vehicula, elit non pellentesque luctus, justo felis pellentesque orci, quis rhoncus ante dolor ultrices libero. Praesent aliquet vestibulum nisl, nec posuere turpis dapibus ac. Donec massa nibh, tristique nec auctor nec, tempor vel risus. Cras metus risus, ultricies et nisl ac, commodo rutrum leo. Quisque volutpat efficitur magna eu iaculis. Phasellus at rutrum ante, lacinia sagittis nulla. Proin ullamcorper elit nec convallis accumsan. Sed fringilla sed urna in tristique. Donec at justo ac augue luctus fermentum. Aenean semper augue sit amet erat imperdiet, sit amet rutrum nisl semper. Donec sit amet sapien a massa finibus pharetra. Quisque efficitur pharetra consequat. Vivamus sed placerat quam. Maecenas et ipsum dictum, fermentum sapien et, suscipit sem. Nunc lacus metus, vestibulum sed tortor efficitur, lacinia vulputate mi.

            Duis quis massa in leo gravida varius bibendum sed lacus. Aenean at rhoncus orci. Quisque porttitor velit ullamcorper nulla ultrices rhoncus. Pellentesque nec justo semper, accumsan ex a, interdum tortor. Ut pretium elementum condimentum. Sed ultrices efficitur erat ut semper. Etiam consectetur, nisi vel dignissim tincidunt, lectus erat porttitor tellus, eget porttitor erat nisl ac odio. Vestibulum augue mi, tempor a vestibulum eu, rutrum eget neque. Donec neque nunc, pellentesque ac risus sit amet, rhoncus tempus diam. Proin vitae lacinia nisl. Nullam quam ex, tempor tincidunt nisi et, rhoncus tristique risus. Pellentesque sed arcu nec erat congue elementum in at magna. Quisque a mauris turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.

            Proin nec lorem a nisi molestie efficitur. Proin blandit velit nec congue mollis. Duis sit amet nisi non massa aliquet hendrerit. Maecenas a congue massa, eget convallis arcu. Sed eu consectetur felis, nec semper arcu. Phasellus lobortis dignissim mauris, eget lobortis mauris tincidunt tincidunt. Quisque vitae dolor quis turpis bibendum eleifend et vitae metus. Integer egestas augue ex, ut porta augue gravida a. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean blandit congue molestie. Nam bibendum nulla sed eleifend aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

            Nullam vulputate gravida tincidunt. Nulla eget mauris sodales, vestibulum velit imperdiet, pulvinar eros. Nulla facilisi. Morbi at libero ac leo semper interdum et a arcu. Vivamus efficitur imperdiet congue. Nullam malesuada nisl augue, vitae facilisis arcu luctus feugiat. Maecenas sed massa cursus, aliquam neque at, sodales odio. Ut in facilisis ex. Mauris tortor sem, convallis sit amet bibendum ac, semper in magna. Proin pretium venenatis enim, eget congue mauris consequat vel.

            Aliquam commodo erat in libero vulputate, lacinia porttitor odio ultricies. Donec mollis elit tincidunt, blandit eros vitae, pulvinar odio. Morbi pharetra turpis est, non gravida elit cursus eu. Nulla mollis orci vitae enim dignissim finibus. Nulla ultrices bibendum augue, eu hendrerit nunc commodo sed. Nam in ex in mauris cursus auctor et eget ligula. Pellentesque eu justo purus. Sed quis mi id orci euismod elementum tincidunt in lacus. Vestibulum vel tristique enim. Suspendisse turpis erat, placerat vel neque et, fermentum finibus quam.

            Proin efficitur libero eget neque tempus facilisis. Mauris in risus mollis, imperdiet tortor vitae, pellentesque lorem. In sit amet varius magna, sit amet vulputate dui. Aliquam tristique tellus facilisis justo sodales, nec venenatis purus euismod. Phasellus egestas eros nec turpis venenatis, et aliquam magna scelerisque. Duis dapibus, risus et semper vehicula, diam risus pretium metus, at ultricies tellus eros tincidunt mauris. Quisque nunc nibh, interdum fermentum ullamcorper blandit, porttitor a ipsum. Sed ac tempor risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent eget enim vitae libero fermentum cursus.

            Etiam ante nisl, viverra nec suscipit a, sagittis ac ipsum. In hac habitasse platea dictumst. Nullam in orci vel est blandit accumsan eget nec ante. Ut rutrum fermentum sodales. Nulla placerat, neque non dictum egestas, purus ipsum vestibulum purus, a consequat odio mauris in felis. Mauris at euismod massa, non ultrices nisl. Donec tempus mauris leo, sed maximus nisl sodales vel. Donec ut suscipit arcu. Ut vitae interdum orci. Maecenas vehicula metus vitae suscipit luctus. Aliquam ut semper ipsum. Fusce non vehicula ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras ut posuere nisi.

            Fusce fringilla tellus et condimentum varius. Proin nec massa tincidunt, maximus eros vitae, feugiat mi. Praesent volutpat nec turpis quis tristique. Praesent tincidunt ante vitae tincidunt ultricies. Nunc facilisis lorem ut nunc dictum sagittis. Aenean eget odio nec justo sodales auctor quis sed lacus. Nunc euismod posuere nisi. Phasellus viverra odio nec magna fermentum, eu porta libero ullamcorper. Nam ultricies magna non tincidunt fringilla. Donec gravida et ex non hendrerit. Ut ornare diam in purus maximus, sed varius sem ullamcorper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed ut cursus lectus. Vestibulum elementum semper lectus, suscipit gravida purus consequat et. Sed gravida massa tellus, scelerisque tempus nisl maximus sed. Vestibulum ullamcorper eleifend urna at ultricies.</p>

      </Section>
    </main>

  )   
}